### ISSUE TITLE
npm version can't be installed.

### ISSUE THREAD

**Issue by ponychicken** [matthewmueller/array#26]
Current version published at npm: 0.3.2

$ npm install array.js@0.3.2

```
npm http GET https://registry.npmjs.org/array.js/0.3.2
npm http 304 https://registry.npmjs.org/array.js/0.3.2
npm http GET https://registry.npmjs.org/emitter-component
npm http 304 https://registry.npmjs.org/emitter-component
npm ERR! Failed resolving git HEAD (git://github.com/component/to-function.git) fatal: ambiguous argument 'getter/fns': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git://github.com/component/to-function.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git://github.com/component/to-function.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git://github.com/component/to-function.git)
npm ERR! Error: Command failed: fatal: ambiguous argument 'getter/fns': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/Cellar/node/0.10.26/bin/node" "/usr/local/bin/npm" "install" "array.js@0.3.2"
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     <snip>
npm ERR! not ok code 0
```

0.2.1 works fine.

**Comment by ponychicken** [comment]
Easiest fix: Update npm with the current version

**Comment by Swatinem** [comment]
I don’t have publish access -_-

**Comment by ponychicken** [comment]
Looks like you have two projects:
https://www.npmjs.org/package/array.js
https://www.npmjs.org/package/array

The latter one is up to date.

**Comment by Swatinem** [comment]
Ok, that explains it. That breakage may remind people to switch to the right project.

**Comment by ponychicken** [comment]
I don't think this is closed yet. There no mention on the old project that it is abandoned and I'm not sure if it is actually useful to keep it there (I mean its flat out broken). It might be better to simply serve a 404, instead of having people scratch their head what's going on.

Not to mention that this should have been simply renamed instead of duplicated in the first place.

**Comment by Swatinem** [comment]
So you would suggest to just unpublish the old name?
@MatthewMueller has to take care of that, I don’t have the proper access.

**Comment by ponychicken** [comment]
Yes. I think that would be the best idea.

**Comment by matthewmueller** [comment]
ohh shoot. yah i guess that's the best approach.. especially if it's broken anyway
